### ISSUE TITLE
Opening photo app opens contact app.

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-photos-v2#42]
This morning, I've updated some apps in my cozy. Then I clicked on the "photo" app image from the main page to open it, but the contact app is opened instead (url is still showing "photos").

http://i.imgur.com/OUcqSIb.jpg

This is permanent (going out of the app and back again still shows the problem)

Opening "contact" triggers an "internal server error"

Not sure where to file the issue, feel free to close it and recreate it elsewhere...

**Comment by aenario** [comment]
Hi, this is a bug that happens sometimes, we are rewritting the controller to avoid it. 

In the meantime, you can start/stop the app and it should solve the problem.

**Comment by dkm** [comment]
I've tried to start/stop both photo & contacts apps without any luck, problem's still here :/

**Comment by aenario** [comment]
Lucas & Zoé are checking the state of your cozy for debugging. When we are done, i will let you know and you can uninstall both apps and reinstall them (that should take care of the problem). Please don't uninstall/install anything in the meantime (~10min)

**Comment by aenario** [comment]
Have you reinstalled yet ? Your cozy appears in the correct state. Is the bug still present ?

**Comment by dkm** [comment]
I didn't touch anything since my last comment. Problem is still present... Little change tough: when I first filed the issue, the image for the photo app was different:
 -before : more or less white box with a red square in the middle
- now: the regular image (picture frame with a cloud inside)

After a forced reload of my main cozy web page, the behavior is back to normal.

**Comment by aenario** [comment]
Ok, so this got fixed somehow. We will keep this in mind for next iteration on the controller. Thanks for reporting.
